import { Projeto } from "../../components/Shared/IProjeto";

export const projetos: Projeto[] = [
  {
    nome: "Sistema de suporte",
    descricao:
      "Sistema de suporte com perfil de usuário Colaborador e Cliente.",
    tags: ["PHP", "Laravel", "Mysql", "Javascript", "HTML", "Blade"],
    github: "https://github.com/Front-LucasRibeiro/support-system",
    private: false,
    linkProjeto: "",
    data: "22/05/2024",
    imagem: "/suporte-system.jpg",
  },
  {
    nome: "Sistema de cadastro de usuários",
    descricao: "Criação de autenticação, api's, validação backend e frontend",
    tags: [
      "NestJS",
      "PostgreSQL",
      "JWT",
      "Joi",
      "VueJS",
      "Sass/scss",
      "HTML",
      "API",
      "Docker",
    ],
    github: "https://github.com/Front-LucasRibeiro/fullstack-app-crud",
    private: false,
    linkProjeto: "",
    data: "17/05/2024",
    imagem: "/system-fullstack.jpg",
  },
  // {
  //   nome: "Sistema de Cadastro com VueJS",
  //   descricao: "Testar com user: admin, password: admin",
  //   tags: ['Javascript', 'HTML','CSS', 'Typescript', 'Vite', 'Sass/scss', 'Vuex', 'Zod', 'API'],
  //   github: "https://github.com/Front-LucasRibeiro/fcc-registration-system",
  //   private: false,
  //   linkProjeto: "",
  //   data: "08/05/2024",
  //   imagem: "/fcc-crud.jpg"
  // },
  {
    nome: "Gráficos",
    descricao: "Criação de gráfico com chart.js",
    tags: ["Javascript", "HTML", "CSS"],
    github: "https://github.com/Front-LucasRibeiro/mirante-tecnologia",
    private: false,
    linkProjeto: "https://front-lucasribeiro.github.io/mirante-tecnologia/",
    data: "29/04/2024",
    imagem: "/grafico.jpg",
  },
  {
    nome: "Rick and Morty",
    descricao: "Listagem de personagens, busca, favoritos, paginação",
    tags: ["Angular", "NgRx", "Rxjs", "Sass/scss", "Typescript", "API"],
    github: "https://github.com/Front-LucasRibeiro/rick-and-morty",
    private: false,
    linkProjeto: "https://rick-and-morty-blue-sigma.vercel.app",
    data: "28/04/2024",
    imagem: "/rick-and-morty.jpg",
  },
  {
    nome: "Portfólio Dev",
    descricao: "Portfólio para mostrar os meus projetos pessoais",
    tags: ["Vite", "ReactJS", "Sass/scss", "Tailwind", "Typescript"],
    github: "https://github.com/Front-LucasRibeiro/portfolio-dev",
    private: false,
    linkProjeto: "https://portfolio-dev-drab.vercel.app/",
    data: "17/04/2024",
    imagem: "/portfolio.jpg",
  },
  {
    nome: "Agendar Aqui",
    descricao:
      "Sistema de Agendamento com banco de dados em MySql, Back-end em NodeJS",
    tags: [
      "ReactJS",
      "Sass/scss",
      "NodeJS",
      "API",
      "MySql",
      "Nginx",
      "VPS",
      "Nodemailer",
    ],
    github: "https://github.com/Front-LucasRibeiro/barber-shop",
    private: true,
    linkProjeto: "https://admin.agendaraqui.com.br/",
    data: "04/04/2024",
    imagem: "/agendar-aqui.jpg",
  },
  {
    nome: "Página de Categoria",
    descricao:
      "Simulando o desenvolvimento de filtro e página de categoria de um e-commerce.",
    tags: [
      "GulpJS",
      "Sass/scss",
      "Typescript",
      "Webpack",
      "HTML",
      "Javascript",
      "API",
    ],
    github: "https://github.com/Front-LucasRibeiro/desenvolvedor-cadastra",
    private: false,
    linkProjeto:
      "https://front-lucasribeiro.github.io/page-category/dist/index.html",
    data: "22/03/2024",
    imagem: "/category-page.jpg",
  },
  {
    nome: "Home Page",
    descricao: "Simulando home page de um e-commerce.",
    tags: ["GulpJS", "Sass/scss", "HTML", "Javascript", "JQuery"],
    github: "https://github.com/Front-LucasRibeiro/teste-maeztra-lucas-maranho",
    private: false,
    linkProjeto:
      "https://front-lucasribeiro.github.io/teste-maeztra-lucas-maranho/",
    data: "13/03/2024",
    imagem: "/home-page.jpg",
  },
  {
    nome: "Sistema de Cadastro",
    descricao:
      "Sistema de Cadastro de produtos e associação de produtos aos clientes.",
    tags: ["VueJS", "Sass/scss"],
    github: "https://github.com/Front-LucasRibeiro/cadastro-data-stone",
    private: false,
    linkProjeto: "https://cadastro-data-stone.vercel.app/cadastro-clientes",
    data: "04/03/2024",
    imagem: "/sistema-cadastro.jpg",
  },
  {
    nome: "Camisetas Mix",
    descricao: "Loja virtual utilizando Wordpress e plugin WooCommerce",
    tags: [
      "PHP",
      "WooCommerce",
      "Wordpress",
      "Sass/Scss",
      "Javascript",
      "JQuery",
      "GulpJS",
    ],
    github: "https://github.com/Front-LucasRibeiro/camisetas-mix",
    private: true,
    linkProjeto: "https://camisetasmix.com.br/",
    data: "01/02/2024",
    imagem: "/camisetas-mix.jpg",
  },
  {
    nome: "Home Page",
    descricao: "Home Page com efeito Parallax em css",
    tags: ["HTML", "CSS", "JQuery"],
    github: "https://github.com/Front-LucasRibeiro/Layout-Barcos",
    private: false,
    linkProjeto: "https://front-lucasribeiro.github.io/Layout-Barcos/",
    data: "24/02/2020",
    imagem: "/home-page-parallax.jpg",
  },
  {
    nome: "Sistema Campeonato Brasileiro",
    descricao: "Geração de resultados de jogos e tabela do campeonato",
    tags: ["HTML", "CSS", "Javascript", "JQuery"],
    github:
      "https://github.com/Front-LucasRibeiro/Sistema-Campeonato-Brasileiro",
    private: false,
    linkProjeto:
      "https://front-lucasribeiro.github.io/Sistema-Campeonato-Brasileiro/brasileirao.html",
    data: "06/11/2019",
    imagem: "/sistema-campeonato-brasileiro.jpg",
  },
];
